Fix strict lint voilations
brightdigit/SyndiKit pull request #67
Opened 2024-01-21 20:32 UTC by devahmedshendy

2024-01-21 21:00 UTC, devahmedshendy commented
@leogdion The fixes here are just the simple fixes, for more fixes like body length, missing docs, I am working on different branch so we don't mess with this one.

2024-01-22 15:08 UTC, leogdion requested changes
This is great. Just a few changes and then let's chat about next steps.

2024-01-22 15:08 UTC, leogdion commented on Sources/SyndiKit/Formats/Media/Podcast/PodcastPerson+Role.swift
>      init?(role: Role) {
go ahead and add SwiftLint disable for cyclomatic complexity and body length

2024-01-22 15:08 UTC, leogdion commented on Sources/SyndiKit/Formats/Media/Podcast/PodcastPerson+Role.swift
>      private init(knownRole: KnownRole) {
go ahead and add SwiftLint disable for cyclomatic complexity

2024-01-22 22:07 UTC, merged